spring.application.name=demo
spring.datasource.url=jdbc:postgrestql://localhost3033/nombredelabd
spring.datasource.username=usuariodeladb
spring.datasource.password=passworddeladb
spring.datasource.driver-class-name=org.PostgrestSQL.driver


#config del JPA
spring.jpa.database-plataform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

